name: Fetch KW Trend (hourly)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"   # 매 정시(UTC) = KST 기준 매시 정각+9분쯤 실행되는 느낌

permissions:
  contents: write

concurrency:
  group: fetch-kw-trend
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 12

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm i

      - name: Run fetch-trend.js
        env:
          YT_KEY_1: ${{ secrets.YT_KEY_1 }}
          YT_KEY_2: ${{ secrets.YT_KEY_2 }}
          YT_KEY_3: ${{ secrets.YT_KEY_3 }}
          YT_KEY_4: ${{ secrets.YT_KEY_4 }}
          YT_KEY_5: ${{ secrets.YT_KEY_5 }}
        run: node scripts/fetch-trend.js

      - name: Commit kw-trend.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/kw-trend.json
          git diff --cached --quiet || git commit -m "chore: update kw-trend.json (hourly)"
          git push
