name: Fetch KW Trend (every 2h)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # UTC 기준 2시간마다

permissions:
  contents: write

concurrency:
  group: fetch_kw_trend
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # exceljs (XLSX 생성/읽기) 설치
      - name: Install deps (exceljs)
        run: npm i exceljs@^4 --no-audit --no-fund

      # (선택) 키 상태 점검 - 실패해도 다음 단계 진행
      - name: Sanity check keys
        shell: bash
        continue-on-error: true
        env:
          YT_KEY_1: ${{ secrets.YT_KEY_1 }}
          YT_KEY_2: ${{ secrets.YT_KEY_2 }}
          YT_KEY_3: ${{ secrets.YT_KEY_3 }}
          YT_KEY_4: ${{ secrets.YT_KEY_4 }}
          YT_KEY_5: ${{ secrets.YT_KEY_5 }}
        run: |
          for i in 1 2 3 4 5; do
            var="YT_KEY_${i}"; val="${!var}"
            if [ -n "$val" ]; then
              echo "$i: len=${#val}, tail=${val: -4}"
            else
              echo "$i: MISSING"
            fi
          done

      - name: Run fetch-trend.js
        env:
          # --- 수집량/윈도우 ---
          RESULT_PAGES_PER_RUN: '2'
          LOOKBACK_DAYS_SEARCH: '14'
          MAX_DAYS_KEEP: '180'

          # --- 한국 타겟팅 ---
          REGION_FILTER: 'KR'
          LANG_PREF: 'ko'
          LANG_STRICT: '1'
          LANG_MIN_HANGUL_RATIO: '0.15'
          CHANNEL_GEO_STRICT: '0'   # 채널 국가까지 제한하려면 '1'

          # --- Prior ---
          PRIOR_ALPHA: '20'
          PRIOR_MIN_BOOST: '0.6'
          PRIOR_MAX_BOOST: '1.4'
          PRIOR_STRONG_THR: '0.70'

          # --- 수동 라벨 (XLSX/CSV 직독) ---
          MANUAL_FROM_REVIEW_CSV: '1'
          CH_MANUAL_CSV_PATH: 'public/ch-manual.csv'
          MANUAL_MODE: 'soft'         # 'soft' 또는 'hard'
          MANUAL_POS_BOOST: '1.6'
          MANUAL_NEG_BOOST: '0.8'

          # --- 리뷰 산출물 (필요 시 1로 켬) ---
          SR_CH_REVIEW: '0'

          # --- 키 로테이터 ---
          YT_KEY_1: ${{ secrets.YT_KEY_1 }}
          YT_KEY_2: ${{ secrets.YT_KEY_2 }}
          YT_KEY_3: ${{ secrets.YT_KEY_3 }}
          YT_KEY_4: ${{ secrets.YT_KEY_4 }}
          YT_KEY_5: ${{ secrets.YT_KEY_5 }}
          KEY_STATUS_PATH: 'public/key-status.json'
        run: node scripts/fetch-trend.js

      - name: Commit trend artifacts
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/*.json || true
          git add public/*.csv  || true
          git add public/*.xlsx || true
          git commit -m "chore: trend/prior/debug artifacts" || echo "Nothing to commit"
          git push || true
