name: Fetch KW Trend (every 2h)

on:
  workflow_dispatch:        # 수동 실행 버튼
  schedule:
    - cron: '0 */2 * * *'   # UTC 기준 2시간마다

permissions:
  contents: write

concurrency:
  group: fetch_kw_trend
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 키 주입 상태 점검(실패해도 다음 단계 진행)
      - name: Sanity check keys
        continue-on-error: true
        env:
          YT_KEY_1: ${{ secrets.YT_KEY_1 }}
          YT_KEY_2: ${{ secrets.YT_KEY_2 }}
          YT_KEY_3: ${{ secrets.YT_KEY_3 }}
          YT_KEY_4: ${{ secrets.YT_KEY_4 }}
          YT_KEY_5: ${{ secrets.YT_KEY_5 }}
        run: |
          for i in 1 2 3 4 5; do
            var="YT_KEY_${i}"; val="${!var}"
            if [ -n "$val" ]; then
              echo "$i: len=${#val}, tail=${val: -4}"
            else
              echo "$i: MISSING"
            fi
          done

      - name: Run fetch-trend.js
        env:
          # === 수집량(요청 기준) ===
          RESULT_PAGES_PER_RUN: '2'     # 카테고리당 페이지 2
          LOOKBACK_DAYS_SEARCH: '14'
          MAX_DAYS_KEEP: '180'

          # === 키 로테이션 ===
          ROTATE_EAGER: '1'             # 성공 시에도 다음 키로 순환
          ROTATOR_COOLDOWN_MIN: '60'     # ← 신규: 403/429 반복 키를 60분 제외
          # ROTATOR_DEBUG: '1'           # (1회 점검 때만 잠깐 켜세요)
          # KEY_STATUS_PATH: 'public/key-status.json'  # (선택) 상태 파일 기록

          # === API KEYS (Secrets) ===
          YT_KEY_1: ${{ secrets.YT_KEY_1 }}
          YT_KEY_2: ${{ secrets.YT_KEY_2 }}
          YT_KEY_3: ${{ secrets.YT_KEY_3 }}
          YT_KEY_4: ${{ secrets.YT_KEY_4 }}
          YT_KEY_5: ${{ secrets.YT_KEY_5 }}
        run: node scripts/fetch-trend.js

      - name: Commit trend artifacts
        if: always()
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/*.json || true
          git commit -m "chore: trend update $(date -u +'%F %T')" || echo "Nothing to commit"
          git push || true
